// src/constants/banks.ts

export const BANKS = [
  "Access Bank",
  "Access Bank (Diamond)",
  "Citibank Nigeria",
  "Ecobank Nigeria",
  "Fidelity Bank",
  "First Bank of Nigeria",
  "First City Monument Bank",
  "Globus Bank",
  "Guaranty Trust Bank",
  "Jaiz Bank",
  "Keystone Bank",
  "Kuda Bank",
  "Lotus Bank",
  "Moniepoint MFB",
  "Opay",
  "PalmPay",
  "Parallex Bank",
  "Polaris Bank",
  "PremiumTrust Bank",
  "Providus Bank",
  "Stanbic IBTC Bank",
  "Standard Chartered Bank",
  "Sterling Bank",
  "Suntrust Bank",
  "TAJ Bank",
  "Titan Bank",
  "Union Bank of Nigeria",
  "United Bank for Africa",
  "Unity Bank",
  "Wema Bank",
  "Zenith Bank",
];

export const BANKS1 = [
  {
    code: "40195",
    name: "78 Finance Company Ltd",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "090629",
    name: "9jaPay Microfinance Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "120001",
    name: "9mobile 9Payment Service Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "404",
    name: "Abbey Mortgage Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51204",
    name: "Above Only MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51312",
    name: "Abulesoro MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "044",
    name: "Access Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "063",
    name: "Access Bank (Diamond)",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "602",
    name: "Accion Microfinance Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "90102",
    name: "Adamawa Mortgage Bank Limited",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50315",
    name: "Aella MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "90077",
    name: "AG Mortgage Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50036",
    name: "Ahmadu Bello University Microfinance Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "120004",
    name: "Airtel Smartcash PSB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51336",
    name: "AKU Microfinance Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "090561",
    name: "Akuchukwu Microfinance Bank Limited",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50055",
    name: "Al-Barakah Microfinance Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "035A",
    name: "ALAT by WEMA",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51074",
    name: "Alert MFB ",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "108",
    name: "Alpha Morgan Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "000304",
    name: "Alternative bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50926",
    name: "Amju Unique MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50083",
    name: "Aramoko MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "401",
    name: "ASO Savings and Loans",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50092",
    name: "Assets Microfinance Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "MFB50094",
    name: "Astrapolaris MFB LTD",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "090478",
    name: "AVUENEGBE MICROFINANCE BANK",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51351",
    name: "AWACASH MICROFINANCE BANK",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51337",
    name: "AZTEC MICROFINANCE BANK LIMITED",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51229",
    name: "Bainescredit MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50117",
    name: "Banc Corp Microfinance Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "11072",
    name: "Bank78 Microfinance Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50572",
    name: "BANKIT MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50572",
    name: "BANKIT MICROFINANCE BANK LTD",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51341",
    name: "BANKLY MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "MFB50992",
    name: "Baobab Microfinance Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51100",
    name: "BellBank Microfinance Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51267",
    name: "Benysta Microfinance Bank Limited",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50122",
    name: "Berachah Microfinance Bank Ltd.",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50123",
    name: "Beststar Microfinance Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50725",
    name: "BOLD MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51449",
    name: "Boost Microfinance Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "650",
    name: "Bosak Microfinance Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50931",
    name: "Bowen Microfinance Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "FC40163",
    name: "Branch International Finance Company Limited",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "90070",
    name: "Brent Mortgage bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50645",
    name: "BuyPower MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "565",
    name: "Carbon",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51353",
    name: "Cashbridge Microfinance Bank Limited",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "865",
    name: "CASHCONNECT MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51437",
    name: "Cedrus MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50823",
    name: "CEMCS Microfinance Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "050032",
    name: "Centrum Finance",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50171",
    name: "Chanelle Microfinance Bank Limited",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "312",
    name: "Chikum Microfinance bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "023",
    name: "Citibank Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "070027",
    name: "CITYCODE MORTAGE BANK",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50910",
    name: "Consumer Microfinance Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51458",
    name: "Cool Microfinance Bank Limited",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "90089",
    name: "Cooperative Mortgage Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50204",
    name: "Corestep MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "559",
    name: "Coronation Merchant Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "FC40128",
    name: "County Finance Limited",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "40119",
    name: "Credit Direct Limited",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51297",
    name: "Crescent MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "090560",
    name: "Crust Microfinance Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50216",
    name: "CRUTECH MICROFINANCE BANK LTD",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51368",
    name: "Dash Microfinance Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51334",
    name: "Davenport MICROFINANCE BANK",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51450",
    name: "Dillon Microfinance Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50162",
    name: "Dot Microfinance Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50922",
    name: "EBSU Microfinance Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "050",
    name: "Ecobank Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50263",
    name: "Ekimogun MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "098",
    name: "Ekondo Microfinance Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51475",
    name: "Ethica MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "090678",
    name: "EXCEL FINANCE BANK",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50126",
    name: "Eyowo",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51318",
    name: "Fairmoney Microfinance Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51241",
    name: "FCMB MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50298",
    name: "Fedeth MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "050002",
    name: "Fewchore Finance Company Limited",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51110",
    name: "FFS Microfinance Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "070",
    name: "Fidelity Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51314",
    name: "Firmus MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "011",
    name: "First Bank of Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "214",
    name: "First City Monument Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50934",
    name: "First Option MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "090164",
    name: "FIRST ROYAL MICROFINANCE BANK",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51333",
    name: "FIRSTMIDAS MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "413",
    name: "FirstTrust Mortgage Bank Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "090567",
    name: "Flutterwave MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "D53",
    name: "Fortress MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "501",
    name: "FSDH Merchant Bank Limited",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "832",
    name: "FUTMINNA MICROFINANCE BANK",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "MFB51093",
    name: "Garun Mallam MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "812",
    name: "Gateway Mortgage Bank LTD",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "00103",
    name: "Globus Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "090574",
    name: "Goldman MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "100022",
    name: "GoMoney",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "090664",
    name: "GOOD SHEPHERD MICROFINANCE BANK",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50739",
    name: "Goodnews Microfinance Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "562",
    name: "Greenwich Merchant Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51276",
    name: "GROOMING MICROFINANCE BANK",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50368",
    name: "GTI MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "058",
    name: "Guaranty Trust Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51251",
    name: "Hackman Microfinance Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50383",
    name: "Hasal Microfinance Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51364",
    name: "Hayat Trust MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "120002",
    name: "HopePSB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51211",
    name: "IBANK Microfinance Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51279",
    name: "IBBU MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51244",
    name: "Ibile Microfinance Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "90012",
    name: "Ibom Mortgage Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50439",
    name: "Ikoyi Osun MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50442",
    name: "Ilaro Poly Microfinance Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50453",
    name: "Imowo MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "415",
    name: "IMPERIAL HOMES MORTAGE BANK",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51392",
    name: "INDULGE MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51462",
    name: "INEBA GOGO MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50457",
    name: "Infinity MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "070016",
    name: "Infinity trust  Mortgage Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "090701",
    name: "ISUA MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "301",
    name: "Jaiz Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "402",
    name: "Jubilee Life Mortgage Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50502",
    name: "Kadpoly MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51308",
    name: "KANOPOLY MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "5129",
    name: "Kayvee Microfinance Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "90028",
    name: "Kebbi Homes Savings and Loans Limited",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "082",
    name: "Keystone Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "899",
    name: "Kolomoni MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "100025",
    name: "KONGAPAY (Kongapay Technologies Limited)(formerly Zinternet)",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50200",
    name: "Kredi Money MFB LTD",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50211",
    name: "Kuda Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "90052",
    name: "Lagos Building Investment Company Plc.",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "091003",
    name: "Lemmy MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "090420",
    name: "Letshego Microfinance Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50549",
    name: "Links MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "031",
    name: "Living Trust Mortgage Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50491",
    name: "LOMA MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "303",
    name: "Lotus Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51444",
    name: "Maal MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "090171",
    name: "MAINSTREET MICROFINANCE BANK",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50563",
    name: "Mayfair MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "90003",
    name: "Mayfresh Mortgage Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50570",
    name: "Mega Microfinance Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "MFB51116M",
    name: "Michael Okpara UniAgric Microfinance Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50304",
    name: "Mint MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "09",
    name: "MINT-FINEX MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "946",
    name: "Money Master PSB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50515",
    name: "Moniepoint MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "120003",
    name: "MTN Momo PSB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "090190",
    name: "MUTUAL BENEFITS MICROFINANCE BANK",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "090679",
    name: "NDCC MICROFINANCE BANK",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51361",
    name: "NET MICROFINANCE BANK",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51142",
    name: "Nigerian Navy Microfinance Bank Limited",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51304",
    name: "NIRSAL MICROFINANCE",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50072",
    name: "Nombank MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "561",
    name: "NOVA BANK",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51371",
    name: "Novus MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50629",
    name: "NPF MICROFINANCE BANK",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51261",
    name: "NSUK MICROFINANACE BANK",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50689",
    name: "Olabisi Onabanjo University Microfinance Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50697",
    name: "OLUCHUKWU MICROFINANCE BANK LTD",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "999992",
    name: "OPay Digital Services Limited (OPay)",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "107",
    name: "Optimus Bank Limited",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51477",
    name: "Pact Microfinance Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "100002",
    name: "Paga",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "999991",
    name: "PalmPay",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "104",
    name: "Parallex Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "311",
    name: "Parkway - ReadyCash",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "090680",
    name: "PATHFINDER MICROFINANCE BANK LIMITED",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51457",
    name: "Paystack MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "100039",
    name: "Paystack-Titan",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50743",
    name: "Peace Microfinance Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51226",
    name: "PECANTRUST MICROFINANCE BANK LIMITED",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51146",
    name: "Personal Trust MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50746",
    name: "Petra Mircofinance Bank Plc",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "MFB51452",
    name: "Pettysave MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "050021",
    name: "PFI FINANCE COMPANY LIMITED",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "268",
    name: "Platinum Mortgage Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "00716",
    name: "Pocket App",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "076",
    name: "Polaris Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50864",
    name: "Polyunwana MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "105",
    name: "PremiumTrust Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50739",
    name: "Prospa Capital Microfinance Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "050023",
    name: "PROSPERIS FINANCE LIMITED",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "101",
    name: "Providus Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51293",
    name: "QuickFund MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "502",
    name: "Rand Merchant Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "090496",
    name: "RANDALPHA MICROFINANCE BANK",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50130",
    name: "Rank MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "90067",
    name: "Refuge Mortgage Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50761",
    name: "REHOBOTH MICROFINANCE BANK",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50994",
    name: "Rephidim Microfinance Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51375",
    name: "Retrust Mfb",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51108",
    name: "Rex Microfinance Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51286",
    name: "Rigo Microfinance Bank Limited",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50767",
    name: "ROCKSHIELD MICROFINANCE BANK",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "125",
    name: "Rubies MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51113",
    name: "Safe Haven MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "40165",
    name: "SAGE GREY FINANCE LIMITED",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50582",
    name: "Shield MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "106",
    name: "Signature Bank Ltd",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51062",
    name: "Solid Allianze MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50800",
    name: "Solid Rock MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51310",
    name: "Sparkle Microfinance Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51429",
    name: "Springfield Microfinance Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "221",
    name: "Stanbic IBTC Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "068",
    name: "Standard Chartered Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "090162",
    name: "STANFORD MICROFINANCE BANK",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50809",
    name: "STATESIDE MICROFINANCE BANK",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "070022",
    name: "STB Mortgage Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51253",
    name: "Stellas MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "232",
    name: "Sterling Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "00305",
    name: "Summit Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "100",
    name: "Suntrust Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50968",
    name: "Supreme MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51056",
    name: "Sycamore Microfinance Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "302",
    name: "TAJ Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51269",
    name: "Tangerine Money",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "109",
    name: "Tatum Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51403",
    name: "TENN",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "677",
    name: "Think Finance Microfinance Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "102",
    name: "Titan Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "090708",
    name: "TransPay MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51118",
    name: "TRUSTBANC J6 MICROFINANCE BANK",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50840",
    name: "U and C MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50840",
    name: "U&C Microfinance Bank Ltd (U AND C MFB)",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "090706",
    name: "UCEE MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51322",
    name: "Uhuru MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51080",
    name: "Ultraviolet Microfinance Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50870",
    name: "Unaab Microfinance Bank Limited",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51447",
    name: "UNIABUJA MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50871",
    name: "Unical MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51316",
    name: "Unilag Microfinance Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50875",
    name: "UNIMAID MICROFINANCE BANK",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "032",
    name: "Union Bank of Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "033",
    name: "United Bank For Africa",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "215",
    name: "Unity Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50880",
    name: "UNIUYO Microfinance Bank Ltd",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "50894",
    name: "Uzondu Microfinance Bank Awka Anambra State",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "050020",
    name: "Vale Finance Limited",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "566",
    name: "VFD Microfinance Bank Limited",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51085",
    name: "Victory MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51355",
    name: "Waya Microfinance Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "035",
    name: "Wema Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51386",
    name: "Weston Charis MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "402001",
    name: "Whitecrust Finance Company",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "100040",
    name: "Xpress Wallet",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51253",
    name: "YCT MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "594",
    name: "Yes MFB",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "00zap",
    name: "Zap",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "057",
    name: "Zenith Bank",
    currency: "NGN",
    type: "nuban",
  },
  {
    code: "51373",
    name: "Zitra MFB",
    currency: "NGN",
    type: "nuban",
  },
];
